# BASIC PYTHON 
# 1. Split this string

In [ ]:
s="Hi there Sam!"
s.split()

['Hi', 'there', 'Sam!']

# 2. Use.format() to print the following string.
# output should be:The diameter of the earth is 12742 kilometer

In [ ]:
planet   ="Earth"
diameter = 12742
print ('The diameter of {} is {} kilometer.'.format(planet,diameter));

The diameter of Earth is 12742 kilometer.

# 3.In this nest dictionary grap the word"hello"

In [ ]:
d={'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
a=lst[3][1][2];
print(a)

['hello']

# Numpy

In [ ]:
import numpy as np

# 4.1 Create an array of 10 zeros?
# 4.2 Create an array of 10 fives?

In [ ]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [ ]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]

# 5. Create an array of all the even integers from 20 to 35

In [ ]:
import numpy as np
array =np.arange(20,35,2)
print("Array of all the even integers from 20 to 35")
print (array)

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]

# 6.Create a 3*3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np
x=np.arange (0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

# 7. Concatinate a and b
# a=np.array([1,2,3]),b=np.array([4,5,6])

In [ ]:
import numpy as np
arr1 =np.array([1,2,3])
arr2 =np.array([4,5,6])
arr =np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]

# Pandas
# 8. Create a dataframe with 3 rows and 2 coloumns

In [ ]:
import pandas as pd

In [ ]:
import pandas as pd
data = [['RIYA',10],['AIRA',15],['DAFI',14]]
df = pd.DataFrame(data,columns=['Name','Age'])
df

   Name  Age
0  RIYA   10
1  AIRA   15
2  DAFI   14

# 9.Generate the series of dates from 1st jan,2023 to 10th feb,2023

In [ ]:
import pandas as pd
dRan1 = pd.date_range(start ='1-1-2023',periods =41)
print(dRan1)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')

# 10.Create 2D list to DataFrame
lists =[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]

In [ ]:
lists = [[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]

In [ ]:
list ={'name':['aaa','bbb','ccc'],'score':[22,25,24]}
df =pd.DataFrame(list,index=['1','2','3'])
df

  name  score
1  aaa     22
2  bbb     25
3  ccc     24